// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //scannerSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  scannerSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Administrar Inventario',
      items: ['Administrar Inventario/scanner'],
    },
    {
      type: 'category',
      label: 'Administrar Productos',
      items: ['Administrar Productos/importar'],
    },
    {
      type: 'category',
      label: 'Administrar Whatsapp',
      items: ['Administrar Whatsapp/controlComprobantes'],
    },
    {
      type: 'category',
      label: 'Informes',
      items: ['Informes/informes1', 'Informes/informes2'],
    },
  ],
   
};

export default sidebars;
